services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\ConfigurationAccess\Setting\Controller\:
    resource: 'Controller/'
    public: true

  OxidEsales\GraphQL\ConfigurationAccess\Setting\Service\ModuleSettingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Setting\Service\ModuleSettingService

  OxidEsales\GraphQL\ConfigurationAccess\Setting\Infrastructure\ModuleSettingRepositoryInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Setting\Infrastructure\ModuleSettingRepository

  OxidEsales\GraphQL\ConfigurationAccess\Setting\Service\ThemeSettingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Setting\Service\ThemeSettingService

  OxidEsales\GraphQL\ConfigurationAccess\Setting\Infrastructure\ThemeSettingRepositoryInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Setting\Infrastructure\ThemeSettingRepository
