imports:
  - { resource: Core/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\ConfigurationAccess\Shared\Service\:
    resource: 'Service/'
    public: true

  OxidEsales\GraphQL\ConfigurationAccess\Shared\Service\CollectionEncodingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Shared\Service\JsonCollectionEncodingService

  OxidEsales\GraphQL\ConfigurationAccess\Shared\Service\LanguageServiceInnterface:
    class: \OxidEsales\GraphQL\ConfigurationAccess\Shared\Service\LanguageService
