services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Controller\:
    resource: 'Controller/'
    public: true

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeSettingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeSettingService

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\ThemeSettingRepositoryInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\ThemeSettingRepository

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\ThemeListInfrastructureInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\ThemeListInfrastructure

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\CoreThemeFactoryInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\CoreThemeFactory

  OxidEsales\GraphQL\ConfigurationAccess\Theme\DataType\ThemeDataTypeFactoryInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\DataType\ThemeDataTypeFactory

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeListServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeListService

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\ThemeSwitchInfrastructureInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Infrastructure\ThemeSwitchInfrastructure

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeSwitchServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeSwitchService
