services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Controller\:
    resource: 'Controller/'
    public: true

  OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeSettingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Theme\Service\ThemeSettingService
