services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\ConfigurationAccess\Module\Controller\:
    resource: 'Controller/'
    public: true

  OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleSettingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleSettingService

  OxidEsales\GraphQL\ConfigurationAccess\Module\DataType\ModuleDataTypeFactoryInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Module\DataType\ModuleDataTypeFactory

  OxidEsales\GraphQL\ConfigurationAccess\Module\Infrastructure\ModuleListInfrastructureInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Module\Infrastructure\ModuleListInfrastructure

  OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleListServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleListService

  OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleActivationServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleActivationService
