services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\GraphQL\ConfigurationAccess\Module\Controller\:
    resource: 'Controller/'
    public: true

  OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleSettingServiceInterface:
    class: OxidEsales\GraphQL\ConfigurationAccess\Module\Service\ModuleSettingService
